### ISSUE TITLE
Upgrade gradle wrapper version to the latest one

### ISSUE THREAD

**Issue by vshat-intellias** [IBashniak/WeatherApp#14]
### Suggested steps
1. Open `WeatherApp/build.gradle`
1. Use `alt`(`option`) + `enter` on this row: `classpath 'com.android.tools.build:gradle:4.0.0'`
1. Use suggestion to upgrade `graddle wrapper`

**Comment by IBashniak** [comment]
fixed 1f3b7181b73a9b0c7ce07c39a0466d9583974b7a

**Comment by vshat-intellias** [comment]
Approved ✅
