### ISSUE TITLE
Remove jcenter() from the build file

### ISSUE THREAD

**Issue by vshat-intellias** [IBashniak/WeatherApp#17]
### Suggested steps
1. Read [this](https://developer.android.com/studio/build/jcenter-migration)
2. Remove `jcenter()` from build file
3. `Sync project with gradle files`
4. Verify that the project still compiles and launches

**Comment by IBashniak** [comment]
can't remove jcenter() due to
build errors

A problem occurred configuring root project 'Weather App'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.5.31/kotlin-gradle-plugin-1.5.31.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.32.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.32/kotlin-stdlib-jdk8-1.4.32.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > com.android.tools.build:gradle:7.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools:sdk-common:30.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools:repository:30.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools.build:aaptcompiler:7.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools.analytics-library:shared:30.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools.lint:lint-model:30.0.3
         project : > com.android.tools.build:gradle:7.0.3 > androidx.databinding:databinding-compiler-common:7.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools.utp:android-test-plugin-host-retention-proto:30.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools.build:builder:7.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools.build:builder-model:7.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools.build:gradle-api:7.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools:sdk-common:30.0.3 > com.android.tools:common:30.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools.build:builder:7.0.3 > com.android.tools.analytics-library:tracker:30.0.3
         project : > com.android.tools.build:gradle:7.0.3 > com.android.tools.build:builder:7.0.3 > com.android.tools.build:manifest-merger:30.0.3

**Comment by vshat-intellias** [comment]
@IBashniak try [this](https://stackoverflow.com/a/67635536) solution

**Comment by IBashniak** [comment]
fixed 624eaa3566feaa807e9287a915488b10011f9e47

**Comment by vshat-intellias** [comment]
Approved ✅
