### ISSUE TITLE
Add `Timber` for logging

### ISSUE THREAD

**Issue by vshat-intellias** [IBashniak/WeatherApp#21]
1. Replace Android's `Log.*` with `timber` calls

**Comment by vshat-intellias** [comment]
Please, resolve comments in https://github.com/IBashniak/WeatherApp/commit/0d27f629c84e293d2d10d9f8a00e1ed6808fa6ac

**Comment by IBashniak** [comment]
> Please, resolve comments in [0d27f62](https://github.com/IBashniak/WeatherApp/commit/0d27f629c84e293d2d10d9f8a00e1ed6808fa6ac)

done

**Comment by vshat-intellias** [comment]
Approved ✅
