### ISSUE TITLE
Write unit tests for `BeaufortScaleTable`

### ISSUE THREAD

**Issue by vshat-intellias** [IBashniak/WeatherApp#5]
### Suggested steps
1. Run `src/test/java/com/ibashniak/weatherapp/ExampleUnitTest.kt` to be sure that tests are configured
1. Create `BeaufortScaleTableTest` file within test directory
1. Write several unit tests to check normal behavior
2. Write unit tests to check corner cases (negative numbers, `Double.NaN`, too small array, etc.)

### Additional materials
- [Understanding Unit Tests for Android in 2021](https://proandroiddev.com/understanding-unit-tests-for-android-in-2021-71984f370240)

**Comment by IBashniak** [comment]
fixed in 9288e37ed85a9e39d5f54edcf4718fd9cfba2a78

**Comment by vshat-intellias** [comment]
Please, fix comments in https://github.com/IBashniak/WeatherApp/commit/9288e37ed85a9e39d5f54edcf4718fd9cfba2a78

**Comment by IBashniak** [comment]
fixed 624eaa3566feaa807e9287a915488b10011f9e47

**Comment by vshat-intellias** [comment]
Approved ✅
