### ISSUE TITLE
Update project dependencies to actual versions

### ISSUE THREAD

**Issue by vshat-intellias** [IBashniak/WeatherApp#6]
### Suggested steps
1. Check `IBashniak/WeatherApp/app/build.gradle` file
1. Use Android Studio suggestions to update dependencies
1. Remove unused dependencies (like `retrofit`)
1. Sync `gradle`
1. Try to launch the application

**Comment by IBashniak** [comment]
fixed 1f3b7181b73a9b0c7ce07c39a0466d9583974b7a

**Comment by vshat-intellias** [comment]
Approved ✅
