### ISSUE TITLE
Create local properties file with an API key

### ISSUE THREAD

**Issue by vshat-intellias** [IBashniak/WeatherApp#7]
### Description
You don't need to commit anything. Just create the required file to make this function work properly:
```groovy
static def getApiKey(){
    Properties props = new Properties()
    props.load(new FileInputStream(new File('secrets.properties')))
    return props['API_KEY']
}
```

Write in the issue comments path to the file, when you will have the task finished.

**Comment by IBashniak** [comment]
done

**Comment by vshat-intellias** [comment]
Write in the issue comments path to the file, when you will have the task finished.

**Comment by IBashniak** [comment]
path to the file is WeatherApp/secrets.properties
example:
API_KEY=0fd732b2980xxxx7fee4axxea9

**Comment by vshat-intellias** [comment]
@IBashniak thank you!

Approved ✅
